version: "3.8"
services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: workshop_postgres
    environment:
      POSTGRES_DB: workshop_db
      POSTGRES_USER: workshop_user
      POSTGRES_PASSWORD: workshop_pass
    ports:
      - "5433:5432" # Host:Container
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U workshop_user -d workshop_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  osm2pgsql:
    image: iboates/osm2pgsql:latest
    depends_on:
      - postgres
    environment:
      - OSM2PGSQL_DATABASE=postgresql://workshop_user:workshop_pass@workshop_postgres:5432/workshop_db
      - PGPASSWORD=workshop_pass
    volumes:
      - ./data:/data
    entrypoint:
      [
        "osm2pgsql",
        "-d",
        "workshop_db",
        "-U",
        "workshop_user",
        "-H",
        "workshop_postgres",
        "-P",
        "5432",
        "/data/sample.pbf",
      ]
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    external: true
